target: snowflake
source_file: C:/Users/Downloads/demo/schema_file.xlsx
result_file: C:/Users/Downloads/demo/                       # folder where generated DDL and logs stored
table_types:
  stage:
    prefix: STG_
    suffix: _temp
    default_cols_position: end
    default_cols: [ META_SOURCENAME VARCHAR(16777216),  META_UPDATED_AT VARCHAR(16777216), META_HASHKEY VARCHAR(16777216) ]
  data_lake:
    prefix: DL_
    suffix: _raw
    default_cols_position: end
    default_cols: [ META_SOURCENAME VARCHAR(16777216),  META_UPDATED_AT TIMESTAMP_NTZ(9), META_HASHKEY VARCHAR(16777216),META_CREATED_AT TIMESTAMP_NTZ(9) ]

column_names: uppercase   #current, lowercase
column_length: 16777216   #length for string types, default current
